#!/usr/bin/env python3
"""Verdicts for the 180 sampled relations, keyed by the sample's `id`.

IMPORTANT — provenance of these verdicts.  They are a *first pass produced by
an LLM assistant*, not an independent expert review.  One of the systems under
evaluation is an LLM, so a reader is entitled to discount a judgement made by
another one.  The `author_verdict` column of the output is deliberately left
empty: the sample is meant to be re-read and signed off by the authors, and only
the confirmed column should be reported as validation.

Scale:
  correct        true of the domain, with the asserted predicate
  plausible      defensible but imprecise or contestable — typically a synonym
                 pair asserted as subsumption, an over-general parent, or an
                 ambiguous label
  uninformative  not false, but carries no domain content: an untyped link, a
                 subsumption under the top concept, or a restatement of the
                 alignment
  incorrect      false of the domain, including part-whole asserted as
                 subsumption and duplicate concepts asserted as sub/superclass

Verdicts were made from the labels plus the *source* ontologies' definitions,
never the merged ontology's own generated comments.
"""

VERDICTS: dict[int, tuple[str, str]] = {
    # ── confOf-ekaw ──────────────────────────────────────────────────────────
    1: ("correct", "a short paper is a paper"),
    2: ("plausible", "a contribution is usually, but not necessarily, a document"),
    3: ("correct", "a conference trip is a social event"),
    4: ("uninformative", "merged#linkTo is an untyped association and asserts no domain content"),
    5: ("correct", "a contributed talk is a working (non-social) event"),
    6: ("correct", "an individual presentation is a working event"),
    7: ("incorrect", "a tutorial chair is an organising-committee role, not a PC member"),
    8: ("incorrect", "ekaw#Conference_ and confOf#Conference denote the same concept; the converse is asserted too, forming a cycle"),
    9: ("incorrect", "a workshop chair is an organising-committee role, not a PC member"),
    10: ("correct", "a country is a location"),
    11: ("plausible", "hinges on whether confOf#Assistant is an academic rank or a conference role"),
    12: ("correct", "an individual presentation is an event"),
    13: ("correct", "a session is a working event"),
    14: ("correct", "a reception is an event"),
    15: ("incorrect", "an administrative event is not a paper"),
    16: ("plausible", "the relation is right but asserted between classes instead of as a restriction"),
    17: ("incorrect", "converse of the same-concept subsumption in id 8"),
    18: ("plausible", "not every working event is scientific"),
    19: ("plausible", "the two Event classes denote the same concept; subsumption under-specifies equivalence"),
    20: ("correct", "a short paper is a paper"),
    21: ("plausible", "converse of id 18; defensible in the other direction"),
    22: ("correct", "a tutorial is an event"),
    23: ("correct", "a participant is a conference participant"),
    24: ("correct", "a city is a location"),
    25: ("plausible", "a poster is a contribution, not necessarily a paper"),
    26: ("uninformative", "links a class to the merged root's duplicate of itself"),
    27: ("plausible", "as id 2"),
    28: ("correct", "a track is a working event"),
    29: ("correct", "a participant is a conference participant"),
    30: ("incorrect", "a session chair is not a PC member"),
    31: ("incorrect", "a country does not 'deal with' a contribution"),
    32: ("correct", "a conference trip is an event"),
    33: ("correct", "a banquet is an event"),
    34: ("correct", "an individual presentation is an event"),
    35: ("correct", "a conference banquet is an event"),
    36: ("correct", "an invited talk is a scientific event"),
    37: ("correct", "a paper is a publication"),
    38: ("uninformative", "untyped merged#linkTo"),
    39: ("correct", "a session is an event"),
    40: ("correct", "a reception is an event"),
    41: ("correct", "a contributed talk is a scientific event"),
    42: ("correct", "a city is a location"),
    43: ("incorrect", "a talk is part of a conference, not a kind of conference"),
    44: ("incorrect", "part-whole asserted as subsumption"),
    45: ("correct", "an individual presentation is an event"),
    46: ("incorrect", "part-whole asserted as subsumption"),
    47: ("correct", "a PC chair is a person"),
    48: ("incorrect", "part-whole asserted as subsumption"),
    49: ("plausible", "role disjointness is a defensible but contestable modelling choice"),
    50: ("correct", "an accepted paper is a paper"),
    51: ("correct", "a contributed talk is an event"),
    52: ("incorrect", "ekaw#Tutorial and ekaw#Tutorial_ are the same concept"),
    53: ("incorrect", "part-whole asserted as subsumption"),
    54: ("incorrect", "part-whole asserted as subsumption"),
    55: ("correct", "a reception is an event"),
    56: ("correct", "an individual presentation is an event"),
    57: ("incorrect", "part-whole asserted as subsumption"),
    58: ("correct", "a conference is a scientific event"),
    59: ("correct", "a short paper is a paper"),
    60: ("uninformative", "untyped merged#linkTo, and the subject is a property"),
    # ── human-mouse ──────────────────────────────────────────────────────────
    61: ("correct", "a thoracic cavity vein is a vein"),
    62: ("incorrect", "triceps surae is the calf group; 'Triceps' denotes triceps brachii — lexical false friend"),
    63: ("correct", "the accessory lobe is a lobe of the right lung"),
    64: ("plausible", "the two labels denote the same cerebellar layer; equivalence, not subsumption"),
    65: ("correct", "the eyelid is an eye appendage"),
    66: ("correct", "the superior gluteal artery is a branch of the internal iliac artery"),
    67: ("correct", "arrector pili is smooth muscle"),
    68: ("incorrect", "a blood vessel is not an organism"),
    69: ("correct", "a foot lumbrical is a muscle"),
    70: ("incorrect", "a retinal lamina is a layer of neural tissue, not a membrane"),
    71: ("correct", "the posterior limiting lamina is Descemet's membrane"),
    72: ("incorrect", "pretracheal (infrahyoid) muscles are neck muscles, not pharyngeal"),
    73: ("correct", "a head muscle is a head-and-neck muscle"),
    74: ("incorrect", "'bulboglandular' does not denote a skeletal muscle"),
    75: ("correct", "respiratory system mucosa is mucosa"),
    76: ("correct", "the vulva is a female reproductive organ"),
    77: ("correct", "gut epithelium is gastrointestinal system epithelium"),
    78: ("uninformative", "subsumption under the top concept"),
    79: ("correct", "the sympathetic trunk is part of the autonomic nervous system"),
    80: ("correct", "the eighth rib is a rib"),
    81: ("correct", "the palatine bone is a viscerocranium bone"),
    82: ("correct", "a trunk bone is a skeletal system part"),
    83: ("correct", "an abdominal aorta branch is an arterial blood vessel"),
    84: ("correct", "the muscles of mastication are skeletal muscles"),
    85: ("plausible", "the spinal component arises from spinal roots, but CN XI is a cranial nerve"),
    86: ("correct", "the auditory cortex is cortex"),
    87: ("correct", "cartilage is a biological tissue"),
    88: ("plausible", "mouse#vein and human#Vein denote the same concept; equivalence, not subsumption"),
    89: ("plausible", "great and long saphenous vein are synonyms"),
    90: ("correct", "a salivary gland is an anatomical structure"),
    91: ("correct", "a vein structure is a venous blood vessel"),
    92: ("correct", "an abdomen/pelvis/perineum vessel is a trunk vessel"),
    93: ("correct", "a carpal bone is a carpal/tarsal bone"),
    94: ("correct", "the superficial sural artery is a branch of the popliteal artery"),
    95: ("incorrect", "an anatomical structure is not a living being"),
    96: ("correct", "the descending limb of Henle's loop is a kidney tubule segment"),
    97: ("incorrect", "the jugular foramen is part of the skull base, not a kind of it"),
    98: ("correct", "an ion channel is subcellular anatomy"),
    99: ("correct", "an aortic arch branch is an artery"),
    100: ("correct", "forelimb skin is skin"),
    101: ("correct", "a neck muscle is a head-and-neck muscle"),
    102: ("correct", "thyroid epithelial tissue is glandular epithelial tissue"),
    103: ("correct", "radius and ulna are long bones"),
    104: ("correct", "a pelvis organ is an abdominal/pelvic/perineum organ"),
    105: ("correct", "the round ligament of the uterus is a ligament"),
    106: ("plausible", "'iliac circumflex artery' is ambiguous — deep is external-iliac, superficial is femoral"),
    107: ("correct", "the vulva is a female reproductive organ"),
    108: ("correct", "the distal convoluted tubule is a renal distal tubule"),
    109: ("correct", "a limb joint is a joint"),
    110: ("correct", "the pudendal vein is a vein"),
    111: ("correct", "an abdomen/pelvis/perineum nerve is a trunk nerve"),
    112: ("correct", "a female reproductive gland/organ is a reproductive organ"),
    113: ("correct", "an abdominal/pelvic/perineum organ is a trunk organ"),
    114: ("correct", "lower back skin is abdomen/pelvis/perineum skin"),
    115: ("correct", "an artery is an anatomical entity"),
    116: ("incorrect", "the palatine bone is part of the skull, not a kind of skull"),
    117: ("correct", "an eye muscle is a muscle"),
    118: ("incorrect", "flat bones are skull, ribs and scapula, not extremity bones"),
    119: ("correct", "the lienal artery is the splenic artery, an arterial blood vessel"),
    120: ("correct", "the clitoral gland is a female reproductive gland"),
    # ── swo-acm ──────────────────────────────────────────────────────────────
    121: ("correct", "FreeBSD is released under the FreeBSD license"),
    122: ("correct", "as id 121"),
    123: ("plausible", "'Technologies' is a very general parent for an image format"),
    124: ("correct", "Agilent produces Agilent software"),
    125: ("correct", "as id 121"),
    126: ("plausible", "distributed retrieval is search-engine architecture rather than a search engine"),
    127: ("plausible", "as id 126"),
    128: ("correct", "design patterns belong to software development"),
    129: ("plausible", "Chromeleon is chromatography software; 'Technologies' is uninformatively general"),
    130: ("correct", "Chrome is software"),
    131: ("correct", "Agilent has Agilent software as a product"),
    132: ("correct", "software development techniques belong to software development"),
    133: ("plausible", "as id 123"),
    134: ("plausible", "JPEG 2000 is an image format; 'Technologies' is over-general"),
    135: ("uninformative", "untyped relatedTo between a DBMS and a file extension"),
    136: ("correct", "a dynamic Bayesian network is a Bayesian network model"),
    137: ("correct", "IDLs are about APIs"),
    138: ("plausible", "as id 129"),
    139: ("correct", "as id 136"),
    140: ("correct", "quantile regression techniques are techniques for quantile regression"),
    141: ("plausible", "CMM is a process-maturity framework; placement under software development is loose"),
    142: ("plausible", "as id 126"),
    143: ("uninformative", "relatedTo between two IRIs for the same concept restates the alignment"),
    144: ("uninformative", "as id 135"),
    145: ("incorrect", "the object is a property, not a concept"),
    146: ("uninformative", "untyped relatedTo to a very general node"),
    147: ("plausible", "a GUI is described by, rather than specified by, GUI languages"),
    148: ("correct", "window managers are about the desktop GUI"),
    149: ("incorrect", "the subject is a property, not a concept"),
    150: ("uninformative", "as id 135"),
    151: ("plausible", "simulator/interpreter is a software notation/tool rather than an architecture"),
    152: ("correct", "government technology policy is computing/technology policy"),
    153: ("correct", "ACM CCS places hypertext creation under document preparation"),
    154: ("correct", "is_version_of and has_version are inverses"),
    155: ("correct", "usage-restricted is a usage clause"),
    156: ("correct", "a usage clause is a clause"),
    157: ("uninformative", "subsumption under the top concept"),
    158: ("correct", "IDS belong under intrusion/anomaly detection"),
    159: ("correct", "as id 152"),
    160: ("correct", "import/export controls are government technology policy"),
    161: ("plausible", "in ACM CCS centralization/decentralization sits under network design, not system management"),
    162: ("correct", "platform-unrestricted is a platform clause"),
    163: ("correct", "ACM CCS places phonology/morphology under NLP"),
    164: ("incorrect", "Microsoft 2002 is directly preceded by 2000, not 98"),
    165: ("incorrect", "R2011a is not directly preceded by R14 — several releases lie between"),
    166: ("correct", "matches the Office sequence; note it reproduces the property's own example annotation"),
    167: ("correct", "optical disks are information storage technology"),
    168: ("incorrect", "R14 is directly preceded by R13, not R12"),
    169: ("correct", "M-Coffee is part of the T-Coffee suite"),
    170: ("correct", "as id 160"),
    171: ("incorrect", "high-speed I/O belongs under communication hardware, not reconfigurable logic/FPGAs"),
    172: ("correct", "ACM CCS places theory of mind under philosophical foundations of AI"),
    173: ("correct", "a number-of-installations clause is a licence clause"),
    174: ("correct", "no-restrictions-on-derivatives is a derivatives-allowed clause"),
    175: ("uninformative", "'Academic field' is a minted, contentless parent"),
    176: ("correct", "intrapage space management is a block/page strategy"),
    177: ("correct", "graphical passwords are an authentication method"),
    178: ("correct", "same-license derivative code is a restriction on derivative software"),
    179: ("correct", "as id 166"),
    180: ("correct", "ACM CCS places sound-based I/O under communication hardware"),
}
